### ISSUE TITLE
Colormaps does not work with latest matplotlib 3.6.3

### ISSUE THREAD

**Issue by wxguy** [pratiman-91/colormaps#1]
Firstly, I should appreciate your effort in collating a large set of scientific colourmaps into a dedicated Python library. I have used it for application and for various other purposes. However, with the latest matplotlib release, I get AttributeError. Minimal example taken from README is as follows:

```
$ python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> matplotlib.__version__
'3.6.3'
>>> import colormaps as cmaps
>>> git clone https://github.com/pratiman-91/colormaps.git
KeyboardInterrupt
>>> cmaps.drought_severity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\JSundar\Downloads\colormaps\colormaps\cmaps.py", line 9251, in drought_severity
    if cname in matplotlib.cm._cmap_registry:
  File "C:\Users\JSundar\miniconda\envs\wrfplot\lib\site-packages\matplotlib\_api\__init__.py", line 224, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib.cm' has no attribute '_cmap_registry'. Did you mean: '_gen_cmap_registry'?
```

It would be nice to update your module to keep up with changes in the upstream matplotlib module.

**Comment by wxguy** [comment]
Ok. Found the issue and got it working. Instead of checking if colormap is available in matplotlib using `_cmap_registry` attribute, you can use `plt.colormaps()` to validate. In the `cmap.py`, you can replace all occurrence of following:

`
matplotlib.cm._cmap_registry
`

with 

`
plt.colormaps()
`

Don't forget to import `matplotlib.pyplot as plt`.

Please do the modification and update to `pip`. Thank you.

**Comment by pratiman-91** [comment]
@wxguy Thank you for using this library, even being barebones. I will update the for the latest `matplotlib`.  I don't know when but probably the upcoming weekend.

**Comment by wxguy** [comment]
Made a pull request at https://github.com/pratiman-91/colormaps/pull/3. Please review and merge, if you find it ok.
